server:
  port: 8083

spring:
  application:
    name: ventas-service
  datasource:
    url: ${VENTAS_DB_URL:jdbc:postgresql://services-db:5432/ventas_db}
    username: ${VENTAS_DB_USER:services_user}
    password: ${VENTAS_DB_PASSWORD:services_password}
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info
